# Generated by Django 5.2.4 on 2025-07-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tblbooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=60, null=True)),
                ('packagename', models.CharField(max_length=20, null=True)),
                ('pprice', models.FloatField(null=True)),
                ('totalprice', models.FloatField(null=True)),
                ('npeople', models.IntegerField(null=True)),
                ('no_of_days', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
