# Generated by Django 5.2.4 on 2025-07-30 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblbooking',
            name='booking_date',
            field=models.DateField(null=True),
        ),
    ]
