# Generated by Django 5.2.4 on 2025-07-31 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0002_tblbooking_booking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblbooking',
            name='bookingdatefor',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tblbooking',
            name='time',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
