# Generated by Django 5.2.4 on 2025-07-28 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblteam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('picture', models.ImageField(null=True, upload_to='static/images/')),
                ('post', models.CharField(max_length=100, null=True)),
                ('experiences', models.TextField(null=True)),
            ],
        ),
    ]
