# Generated by Django 5.2.4 on 2025-07-28 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_tblteam'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblcity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityname', models.CharField(max_length=60, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='static/city/')),
            ],
        ),
        migrations.CreateModel(
            name='tblblogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('title', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='static/blogs/')),
                ('posteddate', models.CharField(max_length=100, null=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.tblcity')),
            ],
        ),
    ]
