# Generated by Django 5.2.4 on 2025-07-29 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_tblcity_tblblogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblregister',
            fields=[
                ('name', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=100, primary_key=True, serialize=False)),
                ('mobile', models.CharField(max_length=20, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='static/userpic')),
                ('password', models.CharField(max_length=50, null=True)),
                ('address', models.TextField(null=True)),
                ('regdate', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tblpackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=50, null=True)),
                ('title', models.TextField(null=True)),
                ('package_info', models.TextField(null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='static/package/')),
                ('price', models.CharField(max_length=200, null=True)),
                ('discounted_price', models.CharField(max_length=200, null=True)),
                ('posted_date', models.DateField(null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.tblcity')),
            ],
        ),
    ]
