# Generated by Django 5.2.4 on 2025-07-29 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_tblregister_tblpackage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblregister',
            name='email',
            field=models.EmailField(default='', max_length=100, primary_key=True, serialize=False),
        ),
    ]
