# Generated by Django 5.2.4 on 2025-07-31 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_tblregister_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblpackage',
            name='discounted_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='tblpackage',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
