# Generated by Django 5.2.4 on 2025-08-01 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_tblpackage_discounted_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblblogs',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tblblogs',
            name='user_pic',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
