# Generated by Django 5.2.4 on 2025-08-01 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_tblblogs_email_tblblogs_user_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblblogs',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
